spring:
  application:
    name: ecuservicies

  datasource:
    url: jdbc:mysql://10.121.6.226:3306/ecuserviciesTest
    username: root
    password: 3cU911@J4V4
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
security:
  jwt:
    secret-key: "1HWfWulsW2pAtEpT2hEZVq3A9meao61MVfeC8zxOb6eV1abc82AU4KH7a2zqL2Mv"
    expiration: 1800000  # 15 minutos
    refresh-token:
      expiration: 604800000 # 1 semana
# logging:
#   level:
#     org.springframework.security: DEBUG
#     org.springframework.security.web.access.intercept: DEBUG
#     io.jsonwebtoken: DEBUG
server:
  port: 8080
  address: 0.0.0.0